CREATE TABLE IF NOT EXISTS faqs (
  id SERIAL PRIMARY KEY,
  q_kh TEXT NOT NULL,
  q_en TEXT NOT NULL,
  a_kh TEXT NOT NULL,
  a_en TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);